String SendHTML() {
  String ptr;
  // Start html
  ptr += "<!DOCTYPE html>\n";
  ptr += "<html lang=\"en\">\n";
  ptr += "<head>\n";
  ptr += "<meta charset=\"UTF-8\">\n";
  ptr += "<meta name=\"viewport\" content=\"min-width=device-width, initial-scale=1.0\">\n";
  ptr += "<title>Document</title>\n";
  ptr += "<style>\n";
  ptr += ":root {\n";
  ptr += "--gap: 64px;\n";
  ptr += "--button-size: 100px;\n";
  ptr += "--text-size: 32px;\n";
  ptr += "--radius: 24px;\n";
  ptr += "}\n";
  ptr += "* {\n";
  ptr += "user-select: none;\n";
  ptr += "}\n";
  ptr += "html,\n";
  ptr += "body {\n";
  ptr += "display: flex;\n";
  ptr += "flex-direction: column;\n";
  ptr += "margin: 0;\n";
  ptr += "width: 100%;\n";
  ptr += "height: 100%;\n";
  ptr += "}\n";
  ptr += "div {\n";
  ptr += "flex: 1;\n";
  ptr += "display: flex;\n";
  ptr += "gap: var(--gap);\n";
  ptr += "justify-content: center;\n";
  ptr += "align-items: center;\n";
  ptr += "}\n";
  ptr += "button {\n";
  ptr += "min-width: var(--button-size);\n";
  ptr += "min-height: var(--button-size);\n";
  ptr += "font-size: var(--text-size);\n";
  ptr += "border-radius: var(--radius);\n";
  ptr += "}\n";
  ptr += "button:active,\n";
  ptr += "button[pressed=\"true\"] {\n";
  ptr += "transform: scale(0.9);\n";
  ptr += "box-shadow: 5px 3px 33px 2px rgba(0, 0, 0, 0.24);\n";
  ptr += "background: rgba(0, 0, 0, 0.2);\n";
  ptr += "}\n";
  ptr += ".flex1 {\n";
  ptr += "flex: 1;\n";
  ptr += "}\n";
  ptr += "</style>\n";
  ptr += "</head>\n";
  ptr += "<body>\n";
  ptr += "<div>\n";
  ptr += "<button id=\"toggleBtn\" onclick=\"toggleButton()\">Off</button>\n";
  ptr += "<button onclick=\"offAll()\">Off All</button>\n";
  ptr += "</div>\n";
  ptr += "<div class=\"flex1\"></div>\n";
  ptr += "<div id=\"button-list\"></div>\n";
  ptr += "<script>\n";
  ptr += "let toggle = false;\n";
  ptr += "let interval = [], status = [];\n";
  ptr += "const ip = location.origin;\n";
  ptr += "const isMobile = navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/Android/i);\n";
  ptr += "const toggledEnabled = [\"↑\", \"↓\"];\n";
  ptr += "const btnTitles = [\"↑\", \"↓\", \"←\", \"→\"];\n";
  ptr += "const activeBtns = [\"W=ON&S=OFF\", \"W=OFF&S=ON\", \"A=ON&D=OFF\", \"A=OFF&D=ON\"];\n";
  ptr += "const inactiveBtns = [\"W=OFF&S=OFF\", \"W=OFF&S=OFF\", \"A=OFF&D=OFF\", \"A=OFF&D=OFF\"];\n";
  ptr += "initiateScript();\n";
  ptr += "function noop() { };\n";
  ptr += "function offAll() {\n";
  ptr += "upressAll();\n";
  ptr += "toggleButton(false);\n";
  ptr += "fetch(`${ip}/state?W=OFF&S=OFF&A=OFF&D=OFF`);\n";
  ptr += "};\n";
  ptr += "function toggleButton(toggled) {\n";
  ptr += "toggle = toggled === undefined ? !toggle : toggled;\n";
  ptr += "document.getElementById(\"toggleBtn\").innerHTML = toggle ? \"On\" : \"Off\"\n";
  ptr += "initiateScript();;\n";
  ptr += "}\n";
  ptr += "function upressAll() {\n";
  ptr += "document.querySelectorAll(\"#button-list button\").forEach(btn => btn.setAttribute(\"pressed\", false));\n";
  ptr += "for (let o = 0; o < status.length; o++) {\n";
  ptr += "status[o] = false;\n";
  ptr += "};\n";
  ptr += "};\n";
  ptr += "function initiateScript() {\n";
  ptr += "const btnList = document.getElementById(\"button-list\");\n";
  ptr += "btnList.innerHTML = \"\";\n";
  ptr += "for (let i = 0; i < activeBtns.length; i++) {\n";
  ptr += "const activeBtn = activeBtns[i];\n";
  ptr += "const inactiveBtn = inactiveBtns[i];\n";
  ptr += "const btnTitle = btnTitles[i];\n";
  ptr += "const btn = document.createElement(\"button\");\n";
  ptr += "fetchOut();\n";
  ptr += "if (toggle && toggledEnabled.includes(btnTitle)) {\n";
  ptr += "btn.ontouchstart = noop;\n";
  ptr += "btn.ontouchend = noop;\n";
  ptr += "btn.onmousedown = noop;\n";
  ptr += "btn.onmouseup = noop;\n";
  ptr += "btn.onclick = () => {\n";
  ptr += "upressAll();\n";
  ptr += "status[i] = !status[i];\n";
  ptr += "btn.setAttribute(\"pressed\", status[i]);\n";
  ptr += "if (status[i]) fetchIn();\n";
  ptr += "else fetchOut();\n";
  ptr += "};\n";
  ptr += "} else {\n";
  ptr += "btn.onclick = noop;\n";
  ptr += "if (isMobile) {\n";
  ptr += "btn.ontouchstart = eventIn;\n";
  ptr += "btn.ontouchend = eventOut;\n";
  ptr += "} else {\n";
  ptr += "btn.onmousedown = eventIn;\n";
  ptr += "btn.onmouseup = eventOut;\n";
  ptr += "};\n";
  ptr += "};\n";
  ptr += "btn.innerHTML = btnTitle;\n";
  ptr += "btnList.append(btn);\n";
  ptr += "function eventIn() {\n";
  ptr += "fetchIn();\n";
  ptr += "interval[i] = setInterval(fetchIn, 500);\n";
  ptr += "};\n";
  ptr += "function eventOut() {\n";
  ptr += "fetchOut();\n";
  ptr += "for (let o = 0; o < interval.length; o++) {\n";
  ptr += "clearInterval(interval[o]);\n";
  ptr += "};\n";
  ptr += "};\n";
  ptr += "function fetchIn() { fetch(`${ip}/state?${activeBtn}`); };\n";
  ptr += "function fetchOut() { fetch(`${ip}/state?${inactiveBtn}`); };\n";
  ptr += "};\n";
  ptr += "};\n";
  ptr += "</script>\n";
  ptr += "</body>\n";
  ptr += "</html>\n";
  // End html

  return ptr;
}